// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeojMIq2H72Ml9xT0V6KhAcgz7E0n7lTs',
    appId: '1:209323178849:web:be5f1d2fbf91088dd7e320',
    messagingSenderId: '209323178849',
    projectId: 'quizzy-a45ed',
    authDomain: 'quizzy-a45ed.firebaseapp.com',
    storageBucket: 'quizzy-a45ed.appspot.com',
    measurementId: 'G-FDYN9VFHTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAufM4FL4gVx6dLs4Am2SkJLKtll6tPaaI',
    appId: '1:209323178849:android:045f824d3daeb55ed7e320',
    messagingSenderId: '209323178849',
    projectId: 'quizzy-a45ed',
    storageBucket: 'quizzy-a45ed.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQjaRUhA3CFeOPy4_2RGJrdNSOWWiMV9Q',
    appId: '1:209323178849:ios:27425df7d5d28b7bd7e320',
    messagingSenderId: '209323178849',
    projectId: 'quizzy-a45ed',
    storageBucket: 'quizzy-a45ed.appspot.com',
    androidClientId: '209323178849-c7kegqlab5mvdvtr9ghl05qu3frrajof.apps.googleusercontent.com',
    iosClientId: '209323178849-eklp0uohl6tnb26h7d399ra2ltmuj2ct.apps.googleusercontent.com',
    iosBundleId: 'com.quizzy.quizzy.RunnerTests',
  );
}
